---
apiVersion: v1
kind: Namespace
metadata:
  name: hello
---
apiVersion: v1
kind: Service
metadata:
  name: hello-kubernetes-svc
  namespace: hello
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app: hello-kubernetes  
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hello-kubernetes-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - http:
      paths:
      - path: /hello
        pathType: Prefix
        backend:
          serviceName: hello-kubernetes-svc
          servicePort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-kubernetes
  namespace: hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-kubernetes
  template:
    metadata:
      labels:
        app: hello-kubernetes
    spec:
      containers:
      - name: hello-kubernetes
        image: rpassmore/hello-kubernetes:1.8
        ports:
        - containerPort: 8080
